# Generated by Django 5.2.3 on 2025-06-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(default='default-sku', max_length=50),
            preserve_default=False,
        ),
    ]
